### ISSUE TITLE
Publish new release based on 1.17 changes in main branch

### ISSUE THREAD

**Issue by slimm609** [tianon/gosu#106]
Are you able to publish a new release for gosu based on the change in the main branch?

**Comment by tianon** [comment]
See https://github.com/tianon/gosu/issues/98, https://github.com/tianon/gosu/pull/101#issuecomment-1062122614, https://github.com/tianon/gosu/pull/102#issuecomment-1062127689, https://github.com/tianon/gosu/pull/102#issuecomment-1069402166, and especially #104.
