### ISSUE TITLE
Use with a non-root user?

### ISSUE THREAD

**Issue by lmakarov** [tianon/gosu#11]
I'm running a container as a non-rot user and using sudo to start some services as root in the `entrypoint.sh` script.
I tried switching to `gosu` instead, however cannot figure out a way to use it as a non-root user.

Consider the following simplified Dockerfile:

```
FROM ubuntu:trusty

RUN apt-get update && \
	apt-get install curl sudo -y

RUN useradd -m -s /bin/bash -g users -G sudo -p docker docker && \
    echo 'docker ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN curl -o /usr/local/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/1.6/gosu-$(dpkg --print-architecture)" && \
	chmod +x /usr/local/bin/gosu

USER docker
```

Build it: `docker build -t non-root-user .`

Next try running something with gosu:

```
$ docker run -it --rm non-root-user gosu root ps aux
error: failed switching to "root": setgroups operation not permitted
```

I can run gosu with sudo though, but... that breaks the whole point of not using sudo:

```
$ docker run -it --rm non-root-user sudo gosu root ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  44988  3144 ?        Ss+  16:10   0:00 sudo gosu root ps aux
root         6  0.0  0.1  15572  2164 ?        R+   16:10   0:00 ps aux
```

**Comment by tianon** [comment]
The main use-case I was solving when I created `gosu` was that of processes that _are_ root, but don't want to be, not the other way around.  However, if you really want to use this solution for the opposite problem, you _should_ be able to set the binary setuid (`chmod +s gosu`), and then run it as any user.  Beware though that there will be no authentication, and that any command is permitted (with intentionally no configurability, which is why I don't recommend this as a real solution unless you're OK with those glaring issues).

**Comment by lmakarov** [comment]
`chmod +s gosu` did not help :(

```
docker@cli:~$ ls -la | grep gosu
-rwsr-sr-x  1 docker users 2698808 Nov 11 21:02 gosu
docker@cli:~$ ./gosu root whoami
error: failed switching to "root": operation not permitted
```

**Comment by tianon** [comment]
If you do `chown root:users gosu` now, then any user in the `users` group should be able to run `gosu`. :smile:

**Comment by lmakarov** [comment]
I wish...

```
docker@cli:~$ sudo chown root:users gosu
docker@cli:~$ ls -la | grep gosu
-rwxr-xr-x  1 root   users 2698808 Nov 11 21:02 gosu
docker@cli:~$ ./gosu root whoami
error: failed switching to "root": operation not permitted
docker@cli:~$ groups
users sudo
```

I'm not able to run `su` either, while `sudo su` works:

```
docker@cli:~$ su
su: must be run from a terminal
docker@cli:~$ sudo su
root@cli:/home/docker#
```

**Comment by tianon** [comment]
Ah, when you did the `chown`, it lost the sticky bit (`-rwxr-xr-x`).

**Comment by lmakarov** [comment]
Good catch, it works now!

```
docker@cli:~$ ls -la | grep gosu
-rwsr-sr-x  1 root   users 2698808 Nov 11 21:02 gosu
docker@cli:~$ ./gosu root whoami
root
```

Thanks @tianon!

**Comment by tianon** [comment]
:metal: !
