### ISSUE TITLE
1.14 -> 1.16 bump has gosu stalling

### ISSUE THREAD

**Issue by grooverdan** [tianon/gosu#125]
https://buildbot.mariadb.org/#/builders/311

The non-amd64 builds before [15496](https://buildbot.mariadb.org/#/builders/311/builds/15496) when I reverted stalled at the point of switching:

```
$ podman ps
CONTAINER ID  IMAGE                                   COMMAND     CREATED         STATUS             PORTS       NAMES
8c3ac947419c  localhost/mariadb-34636-aarch64:latest  mariadbd    10 minutes ago  Up 10 minutes ago              mariadb-container-fail-to-start-options-10256-23243
f234e8d878b3  localhost/mariadb-34623-s390x:latest    mariadbd    5 minutes ago   Up 5 minutes ago               mariadb-container-fail-to-start-options-354-23450
[buildbot@bb-rhel8-docker ~]$ podman logs mariadb-container-fail-to-start-options-10256-23243

2023-04-28 08:23:44+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.10.4+maria~ubu2204 started.
2023-04-28 08:23:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
[buildbot@bb-rhel8-docker ~]$ 
[buildbot@bb-rhel8-docker ~]$ podman logs mariadb-container-fail-to-start-options-10256-23243
2023-04-28 08:23:44+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.10.4+maria~ubu2204 started.
2023-04-28 08:23:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
```

Same switching code as always - https://github.com/MariaDB/mariadb-docker/blob/next/docker-entrypoint.sh#L498

qemu version: qemu-user-static.x86_64                       2:6.0.0-1.fc35

Probably due for an update there. I'll try again looking on Monday, just noting for now.

**Comment by tianon** [comment]
I bet you're seeing the same thing I did that led to:

https://github.com/tianon/gosu/blob/bf158f3b52664ba62de0b561a2bff706fa0e9daf/Dockerfile#L27-L28

:weary:

**Comment by grooverdan** [comment]
I tested 1.16 on native hardware for arm64v8 and s390x  and both started without a problem.

I do plan on testing with qemu a bit more later on newer qemu versions.

**Comment by grooverdan** [comment]
testing 1.17 from about now - https://buildbot.mariadb.org/#/builders/311

**Comment by grooverdan** [comment]
yep, 1.17 has been stable.

**Comment by tianon** [comment]
Nice, thank you for testing and reporting back! 🚀

**Comment by grooverdan** [comment]
hoping I wasn't pre-emptively celebrating :grimacing: 
![image](https://github.com/tianon/gosu/assets/462287/b9f2cf57-b25e-4d37-acc8-b5e21bdf255f)
