### ISSUE TITLE
Usage for we'd admin

### ISSUE THREAD

**Issue by joeblew99** [tianon/gosu#13]
I have a use case where I have a wedadmin and a server. The server is using some golang code to execute a call to the OS asks for the root password. The exec command is installing and uninstalling some services.

So I am wondering if I could use this code to ask the user at the web client level for the system password ?

**Comment by tianon** [comment]
Unfortunately, this isn't at all what you're looking for -- something like `su` or `sudo` is going to be more appropriate there.  This tool actually goes the other direction: I've got a process running as root, and I'd like to run it as non-root (which `sudo` and `su` can do, but have odd behaviors for that use case).
