### ISSUE TITLE
gosu and environment variables

### ISSUE THREAD

**Issue by LukeSkyw** [tianon/gosu#14]
Is this the expected behavior? :

``` shell
root@012249adb596:/# gosu myuser echo $HOME 
/root
```

Shouldn't it be? :

``` shell
root@012249adb596:/# gosu myuser echo $HOME 
/home/myuser
```

Is there a config file where I can define which variable is being replaced by the one from the user's environment?

**Comment by pwaller** [comment]
@LukeSkyw bear in mind that $HOME is evaluated by your shell, where you're running as root. If you want it passed through you will have to do something different, such as `gosu myuser bash -c 'echo $HOME'`.

**Comment by tianon** [comment]
Indeed, I can only echo what @pwaller stated -- what you're seeing is expected thanks to your root shell being what's evaluating `$HOME`:
```console
root@375b50c75bb3:/# echo $HOME
/root
root@375b50c75bb3:/# gosu elasticsearch echo $HOME
/root
root@375b50c75bb3:/# gosu elasticsearch sh -c 'echo $HOME'
/home/elasticsearch
```
```

**Comment by LukeSkyw** [comment]
This is not what I get:
root@326a246f3581:/# gosu myuser sh -c 'echo $HOME'
/root

**Comment by tianon** [comment]
Which version of gosu are you running? (Run with no arguments to find out.)

**Comment by LukeSkyw** [comment]
root@326a246f3581:/# gosu
Usage: gosu user-spec command [args]
   ie: gosu tianon bash
       gosu nobody:root bash -c 'whoami && id'
       gosu 1000:1 id

gosu version: 1.2 (go1.3.3 on linux/amd64; gc)

**Comment by tianon** [comment]
That's pretty ancient; can you try a newer version? :smile:

**Comment by natostanco** [comment]
`$HOME` is correct,  however `$USER` `$USERNAME` `$LOGNAME` still show root

**Comment by tianon** [comment]
Correct -- `$HOME` is the only variable Docker itself sets of those three, so it's the only one `gosu` sets.

For `$USER` and `$USERNAME`, you can probably use `$(id -u)` or `$(id -un)` instead (that's what I usually use, since I've found `$USER` and `$USERNAME` to be wildly inconsistent even outside Docker).
