### ISSUE TITLE
The v17 has many security vulnerables because of Go stdlib

### ISSUE THREAD

**Issue by OlgasAcc** [tianon/gosu#150]
The version is vulnerable because of used Go stdlib v1.18.2:

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/a97f3a79-d001-43c3-8165-637202d29599">
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/0becbc94-0fcc-4d75-bad5-9bb681b180fa">
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/8ec608af-0f90-4b4b-92f5-a02d67a33a98">
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/5c61b846-c47e-4dd5-b2e4-31e022f17842">
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/e457183b-4f8f-4e97-aa17-8b5bec5af407">

Please upgrade the Go stdlib to v1.23 in gosu?

The use case: this is a release blocker for our project because of the postgres image which uses vulnerable gosu v17.

Thanks

**Comment by tianon** [comment]
https://github.com/tianon/gosu/blob/4233b796eeb3ba76c8597a46d89eab1f116188e2/SECURITY.md
