### ISSUE TITLE
Question: Package gosu for popular linux distros ?

### ISSUE THREAD

**Issue by zerthimon** [tianon/gosu#16]
Hello.

Are there any plans to package gosu into .deb and .rpm packages and then put it together with docker packages in the official repos ?

**Comment by tianon** [comment]
It's already available in Debian (https://packages.debian.org/sid/gosu), but only in testing/unstable.  The alternative implementation in `su-exec` (https://github.com/ncopa/su-exec) is available in Alpine 3.3+, and is `gosu`-compatible since version 0.2.

**Comment by zerthimon** [comment]
Thanks @tianon , but, frankly, I was hoping for a gosu package in official docker repo.
So I could replace this : 
```
# grab gosu for easy step-down from root
ENV GOSU_VERSION 1.7
RUN set -x \
	&& apt-get update && apt-get install -y --no-install-recommends ca-certificates wget && rm -rf /var/lib/apt/lists/* \
	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
	&& rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu \
	&& gosu nobody true \
	&& apt-get purge -y --auto-remove ca-certificates wget
```
with this:
```
RUN set -x \
	&& sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \
	&& echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.d/docker.list \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends gosu
```

**Comment by tianon** [comment]
Heh, that'd be interesting, but given that it's not an official Docker project, I don't think it'd be appropriate for it to live in the official Docker repository.  I could look to setup my own simple repo for hosting it, but I can't make any promises relating to available time to do so. :disappointed:

At least for Ubuntu suites, I could probably get a small PPA going on Launchpad without too much fanfare.

**Comment by zerthimon** [comment]
@tianon 
A PPA would work for me: it will suffice both ubuntu and debian (as gosu doesn't depend on ubuntu-specific packages). In ubuntu images it would make the install process even more simple:
```
# grab gosu for easy step-down from root
RUN set -x \
    && add-apt-repository -y ppa:tianon/gosu \
    && apt-get update \
    && apt-get install -y --no-install-recommends gosu
``` 
Sounds great to me.

**Comment by 0rax** [comment]
You may be interested in using packager.io that provide such repository (and for other distribution too), which is what we use for Gogs packaging.

It might be a good idea as its free for opensource project.

**Comment by bszonye** [comment]
There appears to be a PPA for trusty & xenial now, but I cannot actually install to trusty from it. Is there a problem with the PPA or am I doing something wrong? Based on https://launchpad.net/~tianon/+archive/ubuntu/gosu/+packages it looks like there may be a build error.

**Comment by bszonye** [comment]
There are xenial builds but the trusty build has an error:
> Missing build dependencies: golang-github-opencontainers-runc-dev (>= 0.0.4~)

**Comment by zerthimon** [comment]
Hi @tianon have you set up a ppa for gosu yet ?

**Comment by tianon** [comment]
Yeah, see https://launchpad.net/~tianon/+archive/ubuntu/gosu.

**Comment by bszonye** [comment]
Just checked the trusty build on launchpad & it works for me now. Thanks!

**Comment by kaluzki** [comment]
There is now a namespace on docker hub for gosu images

https://hub.docker.com/u/gosu/

You can either extend your image:

* **FROM** [gosu/alpine](https://hub.docker.com/r/gosu/alpine/):[latest](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/latest.Dockerfile) | [3.8](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/3.8.Dockerfile) | [3.7](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/3.7.Dockerfile) | [3.6](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/3.6.Dockerfile) | [3.5](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/3.5.Dockerfile) | [3.4](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/3.4.Dockerfile) | [3.2](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/3.2.Dockerfile) | [3.1](https://github.com/kaluzki/docker/blob/gosu/gosu/alpine/3.1.Dockerfile)
* **FROM** [gosu/ubuntu](https://hub.docker.com/r/gosu/ubuntu/):[latest](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/latest.Dockerfile) | [18.04](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/18.04.Dockerfile) | [bionic](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/bionic.Dockerfile) | [16.04](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/16.04.Dockerfile) | [xenial](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/xenial.Dockerfile) | [14.04](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/14.04.Dockerfile) | [trusty](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/trusty.Dockerfile) | [12.04](https://github.com/kaluzki/docker/blob/gosu/gosu/ubuntu/12.04.Dockerfile)
* **FROM** [gosu/centos](https://hub.docker.com/r/gosu/centos/):[latest](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/latest.Dockerfile) | [7](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/7.Dockerfile) | [7.5](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/7.5.Dockerfile) | [7.4](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/7.4.Dockerfile) | [7.3](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/7.3.Dockerfile) | [7.2](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/7.2.Dockerfile) | [7.1](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/7.1.Dockerfile) | [7.0](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/7.0.Dockerfile) | [6](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/6.Dockerfile) | [6.9](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/6.9.Dockerfile) | [6.8](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/6.8.Dockerfile) | [6.7](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/6.7.Dockerfile) | [6.6](https://github.com/kaluzki/docker/blob/gosu/gosu/centos/6.6.Dockerfile)
* **FROM** [gosu/debian](https://hub.docker.com/r/gosu/debian/):[latest](https://github.com/kaluzki/docker/blob/gosu/gosu/debian/latest.Dockerfile) | [9](https://github.com/kaluzki/docker/blob/gosu/gosu/debian/9.Dockerfile) | [stretch](https://github.com/kaluzki/docker/blob/gosu/gosu/debian/stretch.Dockerfile) | [8](https://github.com/kaluzki/docker/blob/gosu/gosu/debian/8.Dockerfile) | [jessie](https://github.com/kaluzki/docker/blob/gosu/gosu/debian/jessie.Dockerfile) | [7](https://github.com/kaluzki/docker/blob/gosu/gosu/debian/7.Dockerfile) | [wheezy](https://github.com/kaluzki/docker/blob/gosu/gosu/debian/wheezy.Dockerfile)
* **FROM** [gosu/fedora](https://hub.docker.com/r/gosu/fedora/):[latest](https://github.com/kaluzki/docker/blob/gosu/gosu/fedora/latest.Dockerfile) | [28](https://github.com/kaluzki/docker/blob/gosu/gosu/fedora/28.Dockerfile) | [27](https://github.com/kaluzki/docker/blob/gosu/gosu/fedora/27.Dockerfile) | [26](https://github.com/kaluzki/docker/blob/gosu/gosu/fedora/26.Dockerfile)

Or **COPY** the binary from [gosu/assets](https://hub.docker.com/r/gosu/assets/) image 

```docker
FROM your/favorit
COPY --from=gosu/assets /opt/gosu /opt/gosu
RUN /opt/gosu/gosu.install.sh && rm -fr /opt/gosu
...
```

**Comment by tianon** [comment]
This is interesting (and flattering!) but definitely not official!

**Comment by tianon** [comment]
Also, gosu is a single static binary, so I'm a little confused why the
images include/require an installation script?

**Comment by kaluzki** [comment]
Sorry, I didn't mention it.

The installation script is pretty simple, but you can always do it explicitly:

```docker
RUN cp /opt/gosu/1-10/gosu-$(uname -m) /usr/local/bin/gosu
RUN chmod +x /usr/local/bin/gosu
```

**Comment by tianon** [comment]
Several distributions have packaged releases of `gosu` (Alpine Edge, Debian Stretch), so I think I'm going to consider this as closed as I'm going to make it.  If further distribution packagers want to go forward with packaging `gosu`, I'm happy to discuss details with them further (or help support their endeavors). :+1:

**Comment by lookfirst** [comment]
@tianon How about publishing the latest version to jesse backports? I need it for a NodeJS 8 container. https://packages.debian.org/jessie-backports/gosu

**Comment by tianon** [comment]
Jessie has transitioned to LTS, and thus "jessie-backports" is closed.

**Comment by lookfirst** [comment]
@tianon Thanks, had deleted my comment about jesse. Figured out a good enough solution... Just use `8-alpine`, which is Alpine 3.8 and does not have gosu either, but I can just do this: `RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ gosu` Alpine is tiny too...

**Comment by tianon** [comment]
In Alpine I'd suggest checking out `su-exec` instead -- it's 100%
compatible (since su-exec 0.2), available in all recent Alpine releases,
and written in pure C so the binary is a fraction of the size.

**Comment by tianon** [comment]
@kaluzki can you please update https://hub.docker.com/u/gosu/ in some way to make it clear that this is in no way official or supported by the gosu upstream project?  (perhaps update the "website" of the org to point to your comment here?  maybe update the "company" field to make it clear somehow?)

**Comment by kaluzki** [comment]
> @kaluzki can you please update https://hub.docker.com/u/gosu/ in some way to make it clear that this is in no way official or supported by the gosu upstream project? (perhaps update the "website" of the org to point to your comment here? maybe update the "company" field to make it clear somehow?)

you can take over the namespace if you want, i sent an invite to @tianon team

**Comment by tianon** [comment]
If you want to add me to the "owners" team, I'd be happy to make the changes I've proposed for now (and consider using it further in the future). :+1:
