### ISSUE TITLE
Error with gpg at ha.pool.sks-keyservers.net

### ISSUE THREAD

**Issue by ovnicraft** [tianon/gosu#17]
Hi, i am trying to install at debian jessie and this:

```gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4```

its giving:

gpg: keyring `/tmp/tmp.EfjkDu6PA3/secring.gpg' created
gpg: keyring `/tmp/tmp.EfjkDu6PA3/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error

problem with server ?

**Comment by ovnicraft** [comment]
@tianon yes you got me, i confirm  i am behind a firewall (i am at hotel).
BTW thanks for quick answer !

**Comment by JoAngel8** [comment]
Before, we have : 

`+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keyring `/tmp/tmp.OiN4X7QrgC/secring.gpg' created
gpg: keyring `/tmp/tmp.OiN4X7QrgC/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net

gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
ERROR: Service 'sonarqube53' failed to build: The command '/bin/sh -c set -x    && apt-get update && apt-get install -y --no-install-recommends ca-certificates wget && rm -rf /var/lib/apt/lists/*        && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)"  && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc"       && export GNUPGHOME="$(mktemp -d)"         && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4      && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu        && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc   && chmod +x /usr/local/bin/gosu         && gosu nobody true     && apt-get purge -y --auto-remove ca-certificates wget' returned a non-zero code: 2
`

**Comment by JoAngel8** [comment]
I also work behind a firewall.
Thanks, after replace `ha.pool.sks-keyservers.net`

in all your Dokerfile like : 
gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4

Docker-compose success to up my postrgres 9.5 Dockerfile.
Thansk a lot for you answer.

**Comment by srosato** [comment]
Thanks a lot @tianon ! I was also behind corporate firewall, `hkp://p80.pool.sks-keyservers.net:80` worked, but `hkps://hkps.pool.sks-keyservers.net` did not, which, in my case, was expected.

**Comment by nicolas-albert** [comment]
Hi,
I use CircleCI to build docker images. For a same build, I have 2 success and 1 failure for a gpg recv-keys : https://circleci.com/gh/convertigo/docker/270

I don't know if it's a good idea to switch to the unsecured server instead of "broken" secure.

Maybe ha.pool.sks-keyservers.net have a temporary failure …

**Comment by nicolas-albert** [comment]
Ok, I have modified my Dockerfiles to get keys from 3 servers, just in case. It works !

```
( gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEYS" \
  || gpg --keyserver pgp.mit.edu --recv-keys "$GPG_KEYS" \
  || gpg --keyserver keyserver.pgp.com --recv-keys "$GPG_KEYS" )
```
