### ISSUE TITLE
Gosu 1.8 binary release doesnt match architecture

### ISSUE THREAD

**Issue by 0rax** [tianon/gosu#19]
Just realised when upgrade the gosu binary in the Gogs Docker Container that the current binary release for the `armhf` architecture is broken. It seems that the current `gosu-armhf` binary is exactly the same binary as `gosu-amd64`.

![gosu binary file report](https://cloud.githubusercontent.com/assets/2822534/15170063/2c5ef6c2-173a-11e6-8b33-51c9efbe57e2.png)
![gosu armor check](https://cloud.githubusercontent.com/assets/2822534/15170062/2c5de61a-173a-11e6-90ca-73529d4e57df.png)

**Comment by tianon** [comment]
Oh, troubling indeed :cold_sweat:
```console
$ file gosu-*
gosu-amd64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-amd64.asc:   data
gosu-arm64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-arm64.asc:   data
gosu-armel:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-armel.asc:   data
gosu-armhf:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-armhf.asc:   data
gosu-i386:        ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-i386.asc:    data
gosu-ppc64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-ppc64.asc:   data
gosu-ppc64el:     ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-ppc64el.asc: data
```

**Comment by 0rax** [comment]
Oh yeah :/ Hopefully not a lot of people are relying on anything but the amd64 build :/

**Comment by tianon** [comment]
I've deleted the binaries and added a note: https://github.com/tianon/gosu/releases/tag/1.8

Now to figure out what's happened :cry:

**Comment by tianon** [comment]
Here's the set of changes: https://github.com/tianon/gosu/compare/1.7...1.8#diff-3254677a7917c6c01f55212f86c57fbf

So far my hunch is this one:
```diff
-ENV BUILD_FLAGS -v -ldflags -d
+ENV BUILD_FLAGS="-v -ldflags '-d -s -w'"
```

**Comment by tianon** [comment]
Nope, still no good after reverting that.  Might be the switch to Alpine, or strange interaction WRT `eval`. :confused:

**Comment by 0rax** [comment]
Weird, will take a quick look at it, keep you informed if I find anything weird

**Comment by tianon** [comment]
Doh, definitely `eval` being silly.  Will have a fix shortly.

**Comment by tianon** [comment]
Much better:
```console
+ file gosu-amd64 gosu-arm64 gosu-armel gosu-armhf gosu-i386 gosu-ppc64 gosu-ppc64el
gosu-amd64:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
gosu-arm64:   ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
gosu-armel:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
gosu-armhf:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
gosu-i386:    ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
gosu-ppc64:   ELF 64-bit MSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, stripped
gosu-ppc64el: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, stripped
```

**Comment by 0rax** [comment]
Thanks, that's perfect.

I was just gonna suggest you to do that :)

**Comment by tianon** [comment]
I find it really amusing that it took 22 days for anyone to notice, myself included!  Especially since the `build.sh` output includes the contents of the `SHA256SUMS` file, which were all exactly alike (and should've set off alarm bells in my head).

**Comment by tianon** [comment]
https://github.com/tianon/gosu/releases/tag/1.9 :+1:

**Comment by 0rax** [comment]
Well yes, that's what surprised me.

To be fair in my case, I try to check if `gosu` has been updated or not whenever I update somethings related to the Gogs Docker container without following the release themselves. I think a lot of people are not updating it right away.

Thats perfect thanks, will update the version in Gogs !

**Comment by tianon** [comment]
Yeah, I definitely don't upgrade `gosu` in all my own images every single time I update here. :smile:
