### ISSUE TITLE
Gosu/tini for s390x architecture

### ISSUE THREAD

**Issue by gajju26** [tianon/gosu#20]
Hi Tianon,

Is there any support or binary available for gosu and tini (s390x architecture).

Thanks,
Gajanan

**Comment by tianon** [comment]
`tini` is a separate project: https://github.com/krallin/tini/releases (and it appears to be amd64-only, as far as official binaries go, but the code ought to compile reasonably portably)

Regarding official binaries for `gosu`, there's nothing in the code itself preventing it (and it would likely "just work" with either gccgo or Go tip), but until Go 1.7+, we don't get cross-compile for s390x.

See https://github.com/tianon/gosu/blob/6d6a363ab0ef0de22c303889236205b22c64c6be/Dockerfile#L23-L51 for how I currently build for multiple platforms for the official binary releases (which again, should "just work" for `s390x` once Go 1.7+ comes out).

**Comment by tianon** [comment]
This was added in https://github.com/tianon/gosu/pull/28, and should be released shortly with 1.10.
