### ISSUE TITLE
Feature Request chown on mounts

### ISSUE THREAD

**Issue by blaggacao** [tianon/gosu#21]
Gosu, or his brother su-exec are my favorite container entrypoint scripts. I think they should be used more often. Something many people still might have to think about is mount permissions. As docker moves on to named volumes as a mechanism for better persistence management, I see a need for something that I'm still solving by an ugly shellscript:

```
#!/bin/sh
EXECUTE=$1
shift 1

OPTS=`getopt -o u:g::f:: --long user:,group::,folders:: -n 'parse-options' -- "$@"`

if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

echo "$OPTS"
eval set -- "$OPTS"

USER='root'
GROUP='root'
FOLDERS=false

while true; do
  case "$1" in
    -u | --user )
            case "$2" in
                "") USER=false ; shift 2 ;;
                *) USER=$2 ; shift 2 ;;
            esac ;;
    -g | --group )
            case "$2" in
                "") GROUP=false ; shift 2 ;;
                *) GROUP=$2 ; shift 2 ;;
            esac ;;
    -f | --folders )
            case "$2" in
                "") FOLDERS=false ; shift 2 ;;
                *) FOLDERS=$2 ; shift 2 ;;
            esac ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

if [ $FOLDERS != false ] ; then
    echo "Chowning $FOLDERS with $USER:$GROUP recursively..."
    chown -R $USER:$GROUP $FOLDERS
fi
echo "Executing $EXECUTE as $USER..."
exec su-exec $USER $EXECUTE
```

Maybe there is room for a "goperm" or similar?

If not a good idea, please close...

**Comment by tianon** [comment]
Sorry for letting this go unnoticed so long. :disappointed:

In my own opinion, this is definitely not something `gosu` should implement (so I'm closing this), but I think a short shell script is probably a decent solution, or simply using `chown` directly in whatever is invoking `gosu` (which is how we normally handle this in the Docker official images). :+1: :heart:
