### ISSUE TITLE
B42F6819007F00F88E364FD4036A9C25BF357DD4 key not found

### ISSUE THREAD

**Issue by rasekar2000** [tianon/gosu#22]
https://gowalker.org/github.com/tianon/gosu

FROM debian

ENV GOSU_VERSION 1.7
RUN set -x \
 When I run, its not working .. because .. 

```
&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
```

 http://ha.pool.sks-keyservers.net/ This key is not existing as per this website as well.

Can you please give a solution? 
Thanks in advance.

**Comment by tianon** [comment]
I can't seem to reproduce (http://ha.pool.sks-keyservers.net/pks/lookup?op=get&search=0xB42F6819007F00F88E364FD4036A9C25BF357DD4):
```console
$ docker run -it --rm debian:jessie
root@966eb1c9b876:/# gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key BF357DD4: public key "Tianon Gravi <tianon@tianon.xyz>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
root@966eb1c9b876:/# gpg --list-keys
/root/.gnupg/pubring.gpg
------------------------
pub   4096R/BF357DD4 2014-02-28
uid                  Tianon Gravi <tianon@tianon.xyz>
uid                  Tianon Gravi <tianon@debian.org>
uid                  Tianon Gravi <tianon@dockerproject.org>
uid                  Andrew Page (tianon) <andrew@infosiftr.com>
uid                  Andrew Page (tianon) <andrew@vitalroute.com>
uid                  Andrew Page (Tianon Gravi) <admwiggin@gmail.com>
uid                  Tianon Gravi (Andrew Page) <tianon@infosiftr.com>
sub   4096R/769826E6 2014-02-28 [expires: 2017-08-02]

```

**Comment by rasekar2000** [comment]
Let me check it now

**Comment by rasekar2000** [comment]
RajRajen:scripts rajrajen$ docker exec -ti my_ubuntu /bin/bash
<vers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
**gpgkeys: key B42F6819007F00F88E364FD4036A9C25BF357DD4 can't be retrieved**
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
root@dec6710df59e:/data#

**Comment by suckowbiz** [comment]
Quite sure your ubuntu has no correct keyserver available (initally). Take a look how to make it working:
```
[devops:~] 130 $ docker run -it ubuntu bash
root@dc2caa798606:/# gpg --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: no keyserver known (use option --keyserver)
gpg: keyserver receive failed: bad URI
root@dc2caa798606:/# gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: requesting key BF357DD4 from hkp server p80.pool.sks-keyservers.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key BF357DD4: public key "Tianon Gravi <tianon@tianon.xyz>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Comment by rasekar2000** [comment]
Sorry for delayed reply @suckowbiz . checked earlier. .let me start from scratch ubuntu than my custom ubuntu and update you. Thanks for replying .

**Comment by blacktop** [comment]
just started seeing this:

```bash
2016-11-10 22:19:17 (2.92 MB/s) - '/usr/local/bin/gosu.asc' saved [543/543]

+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.eIAjiH
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keybox '/tmp/tmp.eIAjiH/pubring.kbx' created
gpg: keyserver receive failed: No keyserver available
``` 

Using `gliderlabs/alpine:3.4`

**Comment by blacktop** [comment]
**update** is just started working again?

**Comment by rasekar2000** [comment]
It seems gosu is no longer required for alpine3.4 + redis3.2.6 as you can see in 

https://github.com/docker-library/redis/blob/master/3.2/alpine/Dockerfile

https://github.com/docker-library/redis/blob/master/3.2/alpine/docker-entrypoint.sh

And also, i suspect that earlier I was using DockerToolbar for MAC .. but it is causing few issues and hence switched back to VM based docker in my MAC and it is working.

I am leaving it to the team to close this ticket at their convenice.

**Comment by tianon** [comment]
Yeah, if you're on Alpine 3.4+, I'd really recommend checking out `su-exec`, since it's a much smaller alternative written in C which is designed to be feature-compatible, and is available in the Alpine repos. :+1:

**Comment by tnguyen14** [comment]
I am running into this same problem today

```
gpgkeys: key B42F6819007F00F88E364FD4036A9C25BF357DD4 not found on keyserver
```

Is this just a temporary issue that would be resolved eventually somehow?

**Comment by tianon** [comment]
Definitely a temporary/server issue.  The nature of the keyservers is that they constantly share keys between one another, making it essentially impossible to remove a key from the keyserver network once enough servers have shared it.

**Comment by benbro** [comment]
I'm getting an error:
```
key B42F6819007F00F88E364FD4036A9C25BF357DD4 can't be retrieved
```

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/4252, especially https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749 / https://github.com/docker-library/php/pull/666, and thus https://github.com/tianon/pgp-happy-eyeballs (which is how I solve GPG server issues for my own machines, and it's been working very, very reliably for me).
