### ISSUE TITLE
Alpine 3.4 prints 'musl-linux-amd64' for 'dpkg --print-architecture'

### ISSUE THREAD

**Issue by dol** [tianon/gosu#24]
If using the recommended gosu Dockerfile RUN command the build of the docker image will fail, because it tries to download the release file for the architecture 'musl-linux-amd64'.

```
+ dpkg --print-architecture
+ wget -O /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/1.9/gosu-musl-linux-amd64
```

A quick check revealed that ```dpkg --print-architecture``` on alpine:3.4 returns ```musl-linux-amd64``` instead of ```amd64```.

**Comment by tianon** [comment]
Arg, that's annoying, and I'd consider that to be a bug in the "dpkg"
install -- "dpkg --print-architecture" is supposed to print the current
"Debian architecture", which is usually less variable than the gnu-tuple,
which is what that looks like.

However, for Alpine uses, I'd actually recommend just using "su-exec" --
it's functionally equivalent, and available via "apk add" directly in
Alpine 3.4.

**Comment by dol** [comment]
I'll use su-exec. I tried both and wanted to report back the issue.

**Comment by tianon** [comment]
Yeah, it's nice to know about, thanks! :+1:

**Comment by dol** [comment]
If I understand the source code of dpkg correctly the mapping that is returned is the 'Debian arch' column in [triplettable](https://alioth.debian.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=dpkg/dpkg.git;a=blob;f=triplettable;h=abe47261b02f88afb88be567eae698db20719dd0;hb=HEAD). CPU is always the last element. A simple awk would do the trick:
```echo 'musl-linux-<cpu>'|awk -F'-' '{print $NF}'```

**Comment by tianon** [comment]
Oh boo, nice catch!

**Comment by dol** [comment]
Happy to help
