### ISSUE TITLE
Mention chroot as an alternative

### ISSUE THREAD

**Issue by vincentbernat** [tianon/gosu#26]
`chroot` (the one in coreutils) has a `--userspec` option since a long time:

```
$ docker run -it --rm ubuntu:precise chroot --userspec=nobody / ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nobody       1  0.0  0.0   6848  1360 ?        Rs+  08:01   0:00 ps aux
```

If people knew about it, it will make their Dockerfiles far simpler since it's available by default in all regular distributions. It doesn't work on Alpine since this option is not part of busybox.

**Comment by tianon** [comment]
Oh, very interesting; wasn't aware of this option!  Will add a note, thanks! :+1:
