### ISSUE TITLE
When should I use gosu instead of chpst?

### ISSUE THREAD

**Issue by d** [tianon/gosu#29]
Hi this is a n00b question: I've been using `chpst` from `runit` for a long time, like 6 years. I recently came across `gosu`, and it looks very similar to `chpst` (at least on the surface, also the fact that they both `exec` instead of `fork`). So I'm curious to know when would I choose to use `gosu` over `chpst`?

**Comment by tianon** [comment]
IMO if you're already familiar with "chpst" and it's readily available
where you need it, there probably isn't much reason to switch :+1:

**Comment by d** [comment]
Cool. Thanks @tianon !
