### ISSUE TITLE
HOME doesn't get set properly

### ISSUE THREAD

**Issue by klaemo** [tianon/gosu#3]
Hey,
it seems like HOME doesn't get set properly. See the following example (I tried it in a `debian/wheezy` docker container)

```bash
useradd -d /var/lib/couchdb couchdb
```

the user is set up correctly it seems:
```bash
$ su couchdb -c env
[...]
USER=couchdb
HOME=/var/lib/couchdb
[...]
```

but gosu doesn't set HOME correctly
```bash
$ gosu couchdb env
[...]
USER=couchdb
HOME=/root
[...]
```

Am I missing something?

Thanks!

**Comment by vmaatta** [comment]
> Unless I'm mistaken, the current behavior is the same as sudo's behavior, correct?

FWIW, wrong, at least in debian.

```bash
$ sudo -u www-data env
…
USER=www-data
USERNAME=www-data
MAIL=/var/mail/www-data
HOME=/var/www
…
```

There are some differences in the ENV set by `su -c` and `sudo` but they both do set `HOME`.

>  if you need different behavior in an edge case

I.e. expecting `HOME` can't very well be said to be an edge case when both `su -c` and `sudo` do set it.

**Comment by tianon** [comment]
Ok, I'm convinced.  Will be making a fix for this shortly and cutting a new release.

**Comment by klaemo** [comment]
Thanks, tianon!
