### ISSUE TITLE
Support `--preserve-environment`

### ISSUE THREAD

**Issue by elgalu** [tianon/gosu#34]

**Comment by tianon** [comment]
You're going to need to elaborate on your request -- "preserve environment" is already how `gosu` works:
```console
$ sudo A=B C=D ./gosu-amd64 tianon sh -c 'echo $A - $C'
B - D
```

**Comment by elgalu** [comment]
Sorry my bad, apparently (at least in docker) this doesn't work:

```sh
USER root
...
export A=B
sudo ./gosu-amd64 tianon sh -c 'echo $A'
```

But this does:

```sh
USER root
...
export A=B
./gosu-amd64 tianon sh -c 'echo $A' #=> B
```

**Comment by tianon** [comment]
It's the `sudo` that's killing your environment in that example -- try `sudo -E ./gosu...` instead and it should work. :+1:
