### ISSUE TITLE
Failed to build for user.user.GetPasswdFile,GetGroupFile,GetExecUserFile

### ISSUE THREAD

**Issue by dlintw** [tianon/gosu#4]
$ go get github.com/tianon/gosu                                       
# github.com/tianon/gosu
../../tianon/gosu/setup-user.go:24: undefined: user.GetPasswdFile
../../tianon/gosu/setup-user.go:29: undefined: user.GetGroupFile
../../tianon/gosu/setup-user.go:34: undefined: user.GetExecUserFile

$ go version
go version go1.4.2 linux/amd64

**Comment by tianon** [comment]
If you checkout the Dockerfile, you'll see that I actually build with a
very specific, explicit commit of libcontainer.  I'm open to porting to the
new "user" interface, but haven't had a chance to do so yet (especially
since functionally, it's 100% equivalent).
