### ISSUE TITLE
Does gosu handle the case where the user doesn't exist in the host /etc/passwd due to LDAP/AD bindings?

### ISSUE THREAD

**Issue by dragon788** [tianon/gosu#40]
I've been looking for a way to not muck up permissions when mounting files for userland programs run from Docker containers (ie Github-Hub) but every time I find something that seems useful, it fails in an epic manner when I try it on my work laptop where I don't exist in the local /etc/passwd. Since I'm only on the system via sssd/nsswitch for getent calls, there is no record of my user elsewhere that I've found.

**Comment by tianon** [comment]
Nope, `gosu` uses the exact same user/group lookup functions that Docker itself does (which parse `/etc/passwd` and `/etc/group` directly rather than shelling out to PAM/NSS, which is why they don't support LDAP).

What _is_ supported however is using raw IDs (both by Docker and `gosu`), so you could take advantage of the fact that `id(1)` and friends use PAM/NSS (and thus will shell out to LDAP) to look up the appropriate UID/GID directly:
```console
$ echo "$(id -u tianon):$(id -g tianon)"
1000:1000
$ sudo gosu "$(id -u tianon):$(id -g tianon)" id
uid=1000(tianon) gid=1000(tianon) groups=1000(tianon)
```

**Comment by dragon788** [comment]
OK, so I'd need to have an LDAP bind inside the container so that when `gosu` did the `id` lookup it got the same results as outside the container?

Currently if I pass in `-u $(id -u $USER):$(id -g $USER)` it complains because my ID is 1535333686.

**Comment by tianon** [comment]
Yeah, probably -- what's the error you get?  I'm able to use that exact ID without issue:
```console
$ docker run -it --rm -u 1535333686:1535333686 bash id
uid=1535333686 gid=1535333686
```

**Comment by dragon788** [comment]
I think my problem is probably further down the chain because this seems to have fixed the permissions issues, and I think part of my issue was using `-v` to bind mount instead of `--mount type=bind` as I discovered a bug (reported a few times) that using `-v` will actually create the file on the host if it doesn't exist rather than stopping and throwing a warning.

End goal is I'm trying to "fix" your github-hub image so that I can actually use it aliased to git to `git clone tianon/more-awesome-repo` instead of having to keep it unaliased or use `cgit` to run my local system's git for cloning/fetching/pushing, basically anything that interacts with ssh (which also hates no user in /etc/passwd).

https://github.com/tianon/dockerfiles/pull/46

**Comment by tianon** [comment]
Hah!  I see.

I use a script similar to the following for that very thing (adapted slightly because mine is actually two scripts, `docker-run-me` and `hub`, but combined here for your sake):

```bash
#!/usr/bin/env bash
set -Eeuo pipefail

hostToHost() {
	readlink -f "$1"
}
hostToContainer() {
	local path="$(hostToHost "$1")"
	echo "/host/${path#/}"
}

hostPwd="$(hostToHost .)"
hostHome="$(hostToHost "$HOME")"
containerPwd="$(hostToContainer "$hostPwd")"
containerHome="$(hostToContainer "$hostHome")"

dockerArgs=(
	-i --rm
	-v "$hostPwd:$containerPwd"
	-w "$containerPwd"
	-v "$hostHome:$containerHome"
	-e HOME="$containerHome"
	# Docker reads /etc/passwd and /etc/group before mounting volumes
	-u "$(id -u):$(id -g)"
	$(id -G | xargs -n1 echo --group-add)
	-v /etc/passwd:/etc/passwd:ro
	-v /etc/group:/etc/group:ro
	-v /etc/localtime:/etc/localtime:ro
	-e HISTSIZE -e HISTFILE -e HISTFILESIZE -e HISTCMD -e HISTCONTROL

	-v "$HOME/.ssh:$HOME/.ssh:ro" # uhh, ssh(1) is silly
)

tmp="/tmp/$(basename "$(readlink -f "$BASH_SOURCE")")"
mkdir -p "$tmp"
dockerArgs+=( -v "$tmp":/tmp )

if [ -t 1 ]; then
	# if we're not being piped, let's add "-t"
	dockerArgs+=( -t -e TERM )
fi

exec docker run "${dockerArgs[@]}" tianon/github-hub hub "$@"
```

**Comment by tianon** [comment]
Oh, I forgot a couple bits:
```bash
# pass along any HUB_* environment variables
for v in "${!HUB_@}"; do
	dockerArgs+=( -e "$v" )
done

# set a bogus browser so that "hub browse" and friends give a sane one-liner for copy pasting
dockerArgs+=( -e BROWSER='echo google-chrome --new-window' )
```

**Comment by dragon788** [comment]
Nice, I'll definitely use this or a close variant on my personal machine. I think I may be up a creek on the work one where I don't have a local user/group in /etc/passwd /etc/group to even sync into the container, I had started with trying to sync in /etc/passwd when I was getting the failures on my mapping (thanks to `-v`) and my current planned workaround (not yet tested) is to try and add my domain user to a local group and/or /etc/passwd and see what blows up, I think last time I did that it forgot about all my other groups and I had to reimage the machine, but that's why I have spares. :smile: 

Its a shame there isn't a good way to use pam or another `getent` backend to handle this more gracefully.

**Comment by tianon** [comment]
I mean, it's _possible_ you could get away with something crazy like `-v /etc:/etc:ro`, but I don't know whether you'll need to install extra packages in your container in order to get the LDAP call-outs to work properly.

**Comment by dragon788** [comment]
Hmm, interestingly I had ssh somewhat working when I wasn't mapping my UID/GID and was mapping the .ssh into /root/.ssh and was getting prompted for my key's passphrase, and now that I have my SSH_AUTH_SOCK mapped in that would probably work for the short term if I can keep the user as root and just map the GID so my user can still read the files even if it doesn't own them.

**Comment by dragon788** [comment]
I think I cracked it, or at least got it to the point where at long as I'm not trying to execute binaries out of git repositories cloned via the github-hub container I can operate without breaking myself. You can specify the root user but change it's primary GID so that your user on the host can still typically at least read files created unless they are 0600, and most that might have that should be mapped from the host rather than getting created in the container. I was using `--group-add $(id -g $USER)` but that only adds to the list of groups and doesn't cause files created by root to inherit that group, hence the `-u root:$(id -g $USER)` instead which works well enough.

Here lies a code dump for posterity, this is a function defined in my .bash_aliases (may move it to .functions like JessFraz someday). I also discovered that you can create a magic tmpfs through a run option now, if you don't want to "pollute" your host with temp files but you want to avoid warnings about not being able to write tmp.

```
hub(){
        config_volumes=()
        USER_DIR='/root/' # Or use '/' if mapping an imaginary user that won't have a home folder inside
        for config in ${HOME}/.gitconfig*; do 
           config_volumes+="--mount type=bind,source=${HOME}/$(basename $config),target=${USER_DIR}$(basename $config) "; 
        done
        # The space before the final " is SIGNIFICANT for proper concatenation

        docker run -it --rm \
                ${config_volumes[@]} \
                --mount type=bind,source="${HOME}/.ssh/",target="${USER_DIR}.ssh/",readonly \
                --mount type=bind,source="${HOME}/.config/hub",target="${USER_DIR}.config/hub" \
                --mount type=bind,source="$(dirname $SSH_AUTH_SOCK)",target="$(dirname $SSH_AUTH_SOCK)" \
                --mount type=bind,source="$(dirname "$(GITDIR=$(command git rev-parse --git-dir || pwd -P); pushd $GITDIR 2>&1 > /dev/null && pwd -P)")",target="/hub-workspace" \
                -w "/hub-workspace" \
                -e "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" \
                -e "BROWSER=echo google-chrome-stable --new-window" \
                -e "PAGER=less" \
                -u root:$(id -g $USER) \
                --log-driver none \
                --name hub \
                --entrypoint hub \
                github-hub  "$@"
                #tianon/github-hub "$@" 
       # Can't use the upstream to push/fetch/clone until the above mentioned PR #46 w/ ssh gets merged
       # Also the PAGER=less won't work without that getting added into #46 or another PR
}
alias git='hub '
alias cgit='command git ' # This is mostly a failsafe for those times I hork up my container or clone my dotfiles on a new host and I haven't built the github-hub local version of PR #46.
```
