### ISSUE TITLE
debian:jessie docker image can't locate package gosu

### ISSUE THREAD

**Issue by ivandotv** [tianon/gosu#45]
I' aware of the [install documenation](https://github.com/tianon/gosu/blob/master/INSTALL.md) however I was under the impression I could also install the package from official repositories from upstream images (debian, ubuntu)
I'm building from `debian:jessie` and it appears there is no `gosu` package in default repositories
It is present in `debian:stretch` and `debian:stretch-slim` images

**Comment by tianon** [comment]
As can be seen at https://packages.debian.org/stretch/gosu, it's only available in `stretch` and later (unless you also enable `jessie-backports`).
