### ISSUE TITLE
Redirecting STDOUT and STDERR of exec'd process

### ISSUE THREAD

**Issue by jberryman** [tianon/gosu#5]
Feature request: I think I'd like to be able to use `gosu` to redirect either or both of STDOUT and STDERR of the process we exec. Does that sound like it would be useful? We're still trying to figure out our story for logging docker containers so maybe that doesn't make sense.

Anyway I may try to hack on this today, and will submit a pull request if you think that's something that would be useful. Otherwise feel free to close.

**Comment by tianon** [comment]
The STDOUT and STDERR are passed directly through as-is (we don't touch
file descriptors at all), so using shell redirection instead of adding
extra features to "gosu" itself should be sufficient, right?
