### ISSUE TITLE
Please can GOSU Alpine APK package in v3.8/community?

### ISSUE THREAD

**Issue by jgibbarduk** [tianon/gosu#50]
Hi 

We (my company) are making use of gosu in our docker images. We seem to only be able to install it from alpine apk from 'edge/testing' repo. https://pkgs.alpinelinux.org/package/edge/testing/x86/gosu

Please can the gosu package be added to the latest stable (v3.8/community) repo? This would enable us to remove all dependencies on the edge repos. 

Thanks :)
James Gibbard

**Comment by tianon** [comment]
Unfortunately, that package isn't maintained by me (nor do I have much influence over the Alpine release cycle).  I _imagine_ it'll probably be part of v3.9, but I can't say for sure.

In the meantime, I'd recommend checking out `su-exec`, which _is_ in the Alpine release repos and is a pure-C reimplementation of `gosu` (so it ends up with smaller binaries too). :+1:
