### ISSUE TITLE
Architecture name in release binaries is based on dpkg notation 

### ISSUE THREAD

**Issue by ironsteel** [tianon/gosu#6]
Hi, I suggest   architecture name to be based on output from uname -m. Yeah, debian is everywhere but some people might be using different package systems or distributions. It's not a big issue tough, I'm just giving a suggestion. 

Thanks

**Comment by tianon** [comment]
I thought about that, but the problem is that "uname -m" output varies
wildly for variations of ARM. :disappointed:

**Comment by tianon** [comment]
https://github.com/opencontainers/specs/issues/69 actually has a nice long list; here's the relevant ARM section:
> - `arm1136jfs`
> - `arm920t`
> - `arm926ejs`
> - `arm9tdmi`
> - `armv4`
> - `armv4b`
> - `armv4t`
> - `armv4tb`
> - `armv5`
> - `armv5b`
> - `armv5b-vfp`
> - `armv5e`
> - `armv5eb`
> - `armv5eb-vfp`
> - `armv5ehfb-vfp`
> - `armv5ehf-vfp`
> - `armv5e-vfp`
> - `armv5hfb-vfp`
> - `armv5hf-vfp`
> - `armv5t`
> - `armv5tb`
> - `armv5tb-vfp`
> - `armv5te`
> - `armv5teb`
> - `armv5teb-vfp`
> - `armv5tehfb-vfp`
> - `armv5tehf-vfp`
> - `armv5te-vfp`
> - `armv5thfb-vfp`
> - `armv5thf-vfp`
> - `armv5t-vfp`
> - `armv5-vfp`
> - `armv6`
> - `armv6b`
> - `armv6b-novfp`
> - `armv6hf`
> - `armv6hfb`
> - `armv6-novfp`
> - `armv6t`
> - `armv6tb`
> - `armv6tb-novfp`
> - `armv6thf`
> - `armv6thfb`
> - `armv6t-novfp`
> - `armv7a`
> - `armv7ab`
> - `armv7ab-neon`
> - `armv7ahf`
> - `armv7ahfb`
> - `armv7ahfb-neon`
> - `armv7ahf-neon`
> - `armv7ahf-neon-vfpv4`
> - `armv7a-neon`
> - `armv7at`
> - `armv7atb`
> - `armv7atb-neon`
> - `armv7athf`
> - `armv7athfb`
> - `armv7athfb-neon`
> - `armv7athf-neon`
> - `armv7athf-neon-vfpv4`
> - `armv7at-neon`

**Comment by bootstraponline** [comment]
It's common to download gosu like this:

`"https://github.com/tianon/gosu/releases/download/1.7/gosu-$(dpkg --print-architecture)"`

I don't think the name should be changed.

**Comment by andyneff** [comment]
@bootstraponline But dpkg only works on debian. It doesn't help other OSes like Fedora based systems.

Does the `arch` command vary widely on the arms too?

**Comment by tianon** [comment]
`dpkg` works and is available on both Alpine (`apk add --no-cache dpkg`) and Fedora (`dnf install dpkg`) at least -- I expect many folks will be just using a hard-coded arch, but I wanted something that was reasonably easy to script/automate.  It's probably pretty easy to write something that converts `uname -m`'s output into something that's at least "close enough" to `dpkg`'s output to accomplish that too, but the one-liner won't be nearly as simple (and I'm not going to resort to a script for `curl | bash`)

Regarding `arch`, I wasn't aware that even existed, but from my own testing it appears to have exactly the same output as `uname -m` (ie, my `armhf` machine outputs `armv7l`).

**Comment by tianon** [comment]
The man page appears to agree: (https://manpages.debian.org/cgi-bin/man.cgi?query=arch&manpath=Debian+unstable+sid)
```
NAME
       arch - print machine hardware name (same as uname -m)
```

**Comment by joelolsn** [comment]
Abilist 64.
