### ISSUE TITLE
what does 'gosu nobody true' mean?

### ISSUE THREAD

**Issue by pyfreyr** [tianon/gosu#61]
I found `gosu nobody true` in some Dockerfiles (such as redis's [Dockerfile](https://github.com/docker-library/redis/blob/dcc0a2a343ce499b78ca617987e8621e7d31515b/5.0/Dockerfile)), is it needed or for some benifits?

```bash
dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
export GNUPGHOME="$(mktemp -d)"; \
gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
gpgconf --kill all; \
rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
chmod +x /usr/local/bin/gosu; \
gosu nobody true; \
\
apt-get purge -y --auto-remove $fetchDeps
```

**Comment by tianon** [comment]
The usage of the `gosu` binary is `gosu user-spec command [args]` -- so `gosu nobody true` is running the `true` command as the `nobody` user.  It's just a simple way to do a rough smoke test and verify that the downloaded/installed binary is working appropriately. :+1:
