### ISSUE TITLE
HTTP fetch error 60: Peer certificate cannot be authenticated with known CA certificates

### ISSUE THREAD

**Issue by hp685** [tianon/gosu#66]
gpgkeys throws an http fetch error for keyserver hkps://keys.openpgp.org

```
+ gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key BF357DD4 from hkps server keys.openpgp.org
gpgkeys: HTTP fetch error 60: Peer certificate cannot be authenticated with known CA certificates
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by tianon** [comment]
This sounds to me like you've probably got an outdated CA certificates bundle -- what distro are you building on?

**Comment by hp685** [comment]
Using manylinux docker image obtained from https://quay.io/repository/pypa/manylinux2010_x86_64
Its runs CentOS6

**Comment by hp685** [comment]
Also, the previous http schemed keyserver ` ha.pool.sks-keyservers.net` worked correctly until today

**Comment by tianon** [comment]
There might be something in https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification that could help you with the issues with `ha.pool.sks-keyservers.net`, but I'm not sure what's up with CentOS 6 and keys.openpgp.org -- it seems like maybe the `ca-certificates` package in CentOS 6 is too old to verify the Let's Encrypt certificate?

**Comment by tianon** [comment]
(I did validate what you're seeing on a totally vanilla "centos:6"
container as well.)

**Comment by hp685** [comment]
Thanks, let me check the docker-library faq link you provided for any pointers

**Comment by hp685** [comment]
```gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4``` seems to work now. 
Looks like there is some flakiness with pooled sks-keyservers as well.

**Comment by hp685** [comment]
In addition to  hkps://keys.openpgp.org, would it make sense to keep the previous keyserver in the docs  for older platforms and close this?

**Comment by tianon** [comment]
IMO documenting how to choose/use a keyserver is a bit out of scope here.
