### ISSUE TITLE
darwin-amd64 gosu binary

### ISSUE THREAD

**Issue by fahedouch** [tianon/gosu#73]
Hi folks,

is it possible to generate a `darwin-amd64` `gosu`  binary with the actual implementation ?

Cordialy.

**Comment by tianon** [comment]
I've not tested on a Mac (and I'm not sure if the upstream code I'm using has been tested on a Mac), so this would be dependent on that happening.

**Comment by tianon** [comment]
Also very curious what the intended usage is? Isn't running things as root on a Mac pretty rare?

**Comment by fahedouch** [comment]
@tianon  There is not a real need I would have liked to test gosu on mac but it is not possible without the right binary. Finally I used the Dockerfile to make my test :)

**Comment by tianon** [comment]
Sorry for the delay; that's fair enough -- I'd say using Docker is definitely the "right" way to run `gosu` on a Mac (since it's a very Linux-specific tool solving a very specific container problem). :sweat_smile:
