### ISSUE TITLE
[question] restore bash / remove gosu from centos 7

### ISSUE THREAD

**Issue by agusgambina** [tianon/gosu#79]
I made mistake

I executed the following command on a vpc (centos 7)
```
set -x && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.12/gosu-amd64" && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/1.12/gosu-amd64.asc" && export GNUPGHOME="$(mktemp -d)" && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu && chmod +x /usr/local/bin/gosu
```

The problem is that now I am getting the docker output on the bash all the time

Is there a safe way to restore / remove gosu?

Thanks

**Comment by tianon** [comment]
It sounds like you probably just need to run `set +x`, but to remove what you installed is just deleting `/usr/local/bin/gosu`.
