### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by tianon** [tianon/gosu#83]
I've been thinking for a long time about re-licensing this project from GPL-3 to Apache-2.0 (which is probably more accurate/correct anyhow, given that what it imports from is all Apache-2.0).

This project being GPL-licensed has been a barrier for some users trying to convince their organizations that it's OK to use, and I don't think the terms of the GPL have really done anything _for_ this project (and I've read many similar accounts from other projects -- the success stories are far outpaced :disappointed:).

I'm creating this issue to have a place to ping all my wonderful contributors to see if there's any dissent in doing so (and I'd appreciate anyone who's in this list commenting with a "yes" or "no" explicitly - hopefully if you're against this you can provide a little bit of a reason why :smile:).  I've also tried to include a link to a PR of yours that I've merged in case you don't remember contributing. :sweat_smile:

- [x] @bitglue (#8)
- [x] @chenrui333 (#67)
- [x] @elsmorian (#23)
- [x] @JayH5 (#25)
- [x] @kiranmantri (#28)
- [x] @NanXiao (#12)
- [ ] @sebastianwebber (#32)
- [ ] @temtemy (#48)
- [x] @tianon :innocent:
- [x] @xyproto (#7)
- [x] @ydcool (#69)

I also want to express heartfelt thanks to each of you for contributing to whatever it is I've got going on here!!  The meat of this tool is ~80 lines of Go, most of which are comments, whitespace, and boilerplate, so I love that so many folks wanted to and have found ways to contribute in spite of that!  Y'all are awesome. :heart:

**Comment by xyproto** [comment]
The license change is fine with me. Yes. 👍

**Comment by chenrui333** [comment]
🚀 from my side

**Comment by JayH5** [comment]
Yep 👍🏼

**Comment by elsmorian** [comment]
Sounds good to me, yes!

**Comment by bitglue** [comment]
:shipit:

**Comment by NanXiao** [comment]
OK from my side!

**Comment by tianon** [comment]
Thank you all!!  Really appreciate how many of y'all have been willing to respond, and so quickly. :bow:

@sebastianwebber @temtemy @ydcool friendly ping? :innocent: :heart: :pray:

**Comment by ydcool** [comment]
Yes ! 👍

**Comment by tianon** [comment]
@sebastianwebber @temtemy :pray: :innocent: :heart:

**Comment by tianon** [comment]
I would still love explicit affirmative votes here, but I do plan to move forward on this as-is (#32 is essentially reverted in the current latest and #48 is a trivial typo patch).

**Comment by tianon** [comment]
https://github.com/tianon/gosu/releases/tag/1.13 :partying_face:
