### ISSUE TITLE
gosu in entrypoint.sh

### ISSUE THREAD

**Issue by jwillmer** [tianon/gosu#84]
I try to use `gosu` in the creation of a docker image. But when I go inside of the running container I get a root prompt. My understanding is that it should be a 'user' prompt. Some idea what I'm doing wrong?

Dockerfile
```Dockerfile
...
RUN apt-get update \
    && apt-get install -y --no-install-recommends gosu\
    && rm -rf /var/lib/apt/lists/*
     
# verify sudo mode
RUN gosu nobody true

# Create user group and user
RUN groupadd --system --gid 999 --non-unique user
RUN useradd --system --uid 999 --gid 999 --shell $(which bash) user

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

EXPOSE 80/tcp
EXPOSE 443/tcp
CMD ["dotnet", "/app/Example.Core.dll"]
```

entrypoint.sh
```bash
#!/bin/sh
set -e

echo "> Fix wwwroot owner permissions.."
find /app/wwwroot \! -user user -exec chown user:user '{}' +

echo "> Starting dotnet application.."
echo ""
exec gosu user:user "$@"

exec "$@"
```

Entering the container shows the root user
```bash
$ docker exec -it example bash
root@d25f66a7a01d:/app#
```

**Comment by tianon** [comment]
If you run `docker top` on your container, you'll see that the main process should be running as `999:999` -- when you run `docker exec`, you're running with the original container settings, which is `0:0`, and you'll need to either use `docker exec --user` to change that, or `docker exec ... entrypoint.sh bash` instead to run `bash` via the entrypoint.

**Comment by jwillmer** [comment]
I figured it is working like this I was just missing the tools to validate it. Thank you for the description. 

As a side note: It was actually very time consuming to find good examples for using `gosu` in docker. Maybe you could add some examples of just copy my code as an example?
